server:
  port: 8083

user:
  name: ENC(dw7Bd8/fv2EBNN12vu/ZNtlf5fS7EV/hD3dITPmrzshpmwTssLhS9ncUH5EJNpEw)
  age: ENC(3H+Z0YdEp0XkLlW4f7X/wWqgZ7sYBTJzGW4WbXrmzGBWVgDOm1OZUL72oMmJYJlS)
  url: ENC(n1Nqur9/1ynWGb0vg/iJLj2Iix3N3166pPAQKQfxgnaZFBcjuAiJ2jHOKCRadEFN2mOabdlPlKpH2Jj33pJ+hQ==)
